// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClz6mBAvwwreBJ3WyZwG6ihj3DByYsNCw',
    appId: '1:1026624653346:web:f598efd3b9722169cd627b',
    messagingSenderId: '1026624653346',
    projectId: 'health-track-app-e01e3',
    authDomain: 'health-track-app-e01e3.firebaseapp.com',
    storageBucket: 'health-track-app-e01e3.firebasestorage.app',
    measurementId: 'G-CYTGPPF6HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAenvChEhJois29Gd1Rrn8Tg6Sj6eXE5Js',
    appId: '1:1026624653346:android:26704975df581629cd627b',
    messagingSenderId: '1026624653346',
    projectId: 'health-track-app-e01e3',
    storageBucket: 'health-track-app-e01e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6gKpRICpbSZ3RcaVZXB4pQ6qoh84Ba70',
    appId: '1:1026624653346:ios:7a1624bf248d55c6cd627b',
    messagingSenderId: '1026624653346',
    projectId: 'health-track-app-e01e3',
    storageBucket: 'health-track-app-e01e3.firebasestorage.app',
    iosBundleId: 'com.example.healthTrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6gKpRICpbSZ3RcaVZXB4pQ6qoh84Ba70',
    appId: '1:1026624653346:ios:7a1624bf248d55c6cd627b',
    messagingSenderId: '1026624653346',
    projectId: 'health-track-app-e01e3',
    storageBucket: 'health-track-app-e01e3.firebasestorage.app',
    iosBundleId: 'com.example.healthTrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClz6mBAvwwreBJ3WyZwG6ihj3DByYsNCw',
    appId: '1:1026624653346:web:c3d918fb63337282cd627b',
    messagingSenderId: '1026624653346',
    projectId: 'health-track-app-e01e3',
    authDomain: 'health-track-app-e01e3.firebaseapp.com',
    storageBucket: 'health-track-app-e01e3.firebasestorage.app',
    measurementId: 'G-YLVHT3RZKZ',
  );
}
